[project]
name = "encore-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "anyio>=4.10.0",
    "mcp[cli]>=1.13.1",
    "requests>=2.32.5",
]
